#!/bin/bash

if [ $# -eq 0 ]
then
  echo "Provide a path to a folder containing .wav's to be analyzed. A JSON file will be written to <basename of folder provided>.json"
  exit 1
fi

if [ $1 == "-h"  ]
then
  echo "Provide a path to a folder containing .wav's to be analyzed. A JSON file will be written to <basename of folder provided>.json"
  exit 1
fi

echo "Conducting meyda analysis..."
for filename in $1*.wav; do
    # for ((i=0; i<=3; i++)); do
    #     ./MyProgram.exe "$filename" "Logs/$(basename "$filename" .txt)_Log$i.txt"
    # done
    f=$(basename -- "$fullfile")
    e="${filename##*.}"
    f="${filename%.*}"
    # echo $f.json
    meyda $filename loudness spectralCentroid amplitudeSpectrum rms spectralFlatness --o=$f.json --format=json
done

echo "Conducting high-level feature analysis"

f=$(basename $1)

node high-level-analyze/high-level-analyze.js $1 $1/$f.json

# uhg windows, it hurts -- UNTESTED HEADS UP
sed 's/\\\\/\//g' $1/$f.json > tmp1234plzdontbeanotherfile.json
mv tmp1234plzdontbeanotherfile.json $1/$f.json
